export const SET_AUTH_LOADER = 'SET_AUTH_LOADER';

// brand
export const SET_INDUSTRY_FIELD = 'SET_INDUSTRY_FIELD';
export const SET_SORTING_TYPE = 'SET_SORTING_TYPE';
export const SET_SEARCH_INPUT = 'SET_SEARCH_INPUT';
export const SET_SAVED_BRAND_LIST = 'SET_SAVED_BRAND_LIST';
export const UPDATE_SAVED_BRAND_LIST = 'UPDATE_SAVED_BRAND_LIST';
export const CLEAR_SAVED_BRAND_LIST = 'CLEAR_SAVED_BRAND_LIST';
export const SET_FILTERED_LIST = 'SET_FILTERED_LIST';
export const UPDATE_FILTERED_LIST = 'UPDATE_FILTERED_LIST';
export const CLEAR_FILTERED_LIST = 'CLEAR_FILTERED_LIST';
export const SET_BRAND_LIST = 'SET_BRAND_LIST';
export const UPDATE_BRAND_LIST = 'UPDATE_BRAND_LIST';
export const CLEAR_BRAND_LIST = 'CLEAR_BRAND_LIST';
export const SET_FILTERED_BRAND_CARD = 'SET_FILTERED_BRAND_CARD';
export const UPDATE_FILTERED_BRAND_CARD = 'UPDATE_FILTERED_BRAND_CARD';
export const CLEAR_FILTERED_BRAND_CARD = 'CLEAR_FILTERED_BRAND_CARD';
// User
export const SET_USER_LOADING = 'SET_USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USER_SETTING_INPUT = 'SET_USER_SETTING_INPUT';
export const UPDATE_USER_SETTING_INPUT = 'UPDATE_USER_SETTING_INPUT';
export const CLEAR_USER_SETTING_INPUT = 'CLEAR_USER_SETTING_INPUT';

//Message
export const SET_RES_SUCCESS_MSG = 'SET_RES_SUCCESS_MSG';
export const SET_RES_ERROR_MSG = 'SET_RES_ERROR_MSG';
export const SET_RES_WARNING_MSG = 'SET_RES_WARNING_MSG';
export const CLEAR_RES_MSG = 'CLEAR_RES_MSG';
