// export const CONTENTFUL_SPACE_ID = process.env.CONTENTFUL_SPACE_ID;
// export const CONTENTFUL_ACCESS_TOKEN = process.env.CONTENTFUL_ACCESS_TOKEN;
export const NEXT_PUBLIC_FIREBASE_CONFIG = process.env.NEXT_PUBLIC_FIREBASE_CONFIG;
