# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Production CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install project dependencies
        run: yarn
      - name: Create env file
        run: |
          touch .env
          echo NODE_ENV=production >> .env
          echo DB_CONNECTION_STRING="${{ secrets.DB_CONNECTION_STRING }}" >> .env
          echo EXPRESS_SECRET=${{ secrets.EXPRESS_SECRET }} >> .env
          echo GRAFANA_API_DNS_URL=${{ secrets.GRAFANA_API_DNS_URL }} >> .env
          echo GRAFANA_API_USERNAME=${{ secrets.GRAFANA_API_USERNAME }} >> .env
          echo GRAFANA_API_KEY=${{ secrets.GRAFANA_API_KEY }} >> .env
          echo GRAFANA_LOG_APP_NAME=${{ secrets.GRAFANA_LOG_APP_NAME }} >> .env
          echo ERP_API_URL=${{ secrets.ERP_API_URL }} >> .env
          cat .env
      - name: Build
        run: yarn build
      - run: npm install -g firebase-tools
      - name: Deploy function
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --only functions:api
        env:
          CI: false
